export interface liveMatch {
    liveId?: number,
    memberId?: number,
    place: string,
    lat?: number,
    lng?: number,
    sportType?: string,
    detail: string,
    hostId: number,
    hostNickName: string,
    currentPeopleNum: number,
    totalPeopleNum: number,
    registTime: string,
    memberList?: number[] | null,
}